In [5]:
import numpy as np



In [7]:
one_dim = np.array([1, 2, 3, 4, 5, "test"])
print(one_dim)

['1' '2' '3' '4' '5' 'test']


In [10]:
two_dim = np.array([ [1,2], [3,4]])
print(two_dim)

[[1 2]
 [3 4]]


In [18]:
zero_arr = np.zeros([2, 3])
one_arr = np.ones([1,2,3])
print(zero_arr)
print(one_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[[1. 1. 1.]
  [1. 1. 1.]]]


In [21]:
sequence_nums = np.arange(1, 5)
print(sequence_nums)

[1 2 3 4]


In [33]:
rands = np.random.randint(low=1, high=5, size=(20,))
print(rands)
print(rands.shape)
rands = np.random.randint(low=1, high=5, size=(2,2))
print(rands.shape)

[2 4 3 2 1 3 4 2 4 1 4 2 4 1 4 3 4 2 1 2]
(20,)
(2, 2)


In [29]:
# Task 1
feature = np.arange(6, 21)
print(feature)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [32]:
label = np.dot(3, feature) + 4
# or
label = 3 * feature + 4
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [40]:
# noise = np.random.randint(low=-2.0, high=3.0, size=(15,))
# print(noise)
# print(label+noise)

noise = np.random.random([15])*4-2
print(noise)
label = label + noise 
print(label)

[-1.74480987  1.95725488  0.51225377 -1.42723537 -0.68295742  0.44847224
 -0.14043794  1.66323971 -1.3532901   0.76253586  1.56682238 -1.82089745
  1.0438433   0.91353866 -1.3473718 ]
[22.40364666 28.82927373 29.17742476 28.82898128 33.07987097 39.18824063
 41.95154331 45.85172903 43.62250994 50.68305194 53.55766599 53.95566738
 60.8434767  60.64817062 63.36361274]
